### ISSUE TITLE
build strategy Docker is not allowed

### ISSUE THREAD

**Issue by hristo-yordanov** [amida-tech/elk-openshift-aws#1]
Hi,

I tryied to execute oc commmand:

> oc new-app https://github.com/amida-tech/elk-openshift-aws --context-dir=kibana --name=kibana

on openshift 3.7 (free web version) and got the next statment:

--> Creating resources ...
    imagestream "kibana" created
    error: buildconfigs.build.openshift.io "kibana" is forbidden: build strategy Docker is not allowed
    deploymentconfig "kibana" created
    service "kibana" created
--> Failed

**Comment by hristo-yordanov** [comment]
I think this is the reason for the issue: OpenShift developer preview does not support Docker builds for security reasons, and the cluster-admin role is not available to end users.

**Comment by jsachs** [comment]
Hey @tvorikod, I believe you are correct. We have been using this on our self-hosted cluster. Also please note that this repo is far from production ready--I have basically been using it as a scratchpad for some experimentation.
